TARGET = main
OBJS = main.o game.o player.o psp.o

PSPSDK = $(shell psp-config --pspsdk-path)
PSPPREFIX = $(shell psp-config --psp-prefix)
SDL_CONFIG = $(PSPPREFIX)/bin/sdl-config

CFLAGS = -Wall -Wextra
CXXFLAGS = $(CFLAGS)

LIBDIR = -I$(PSPPREFIX)/include/SDL
LIBS = $(shell $(SDL_CONFIG) --libs)

EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = Main
PSP_EBOOT_ICON = ICON0.PNG

include $(PSPSDK)/lib/build.mak
