TARGET = main
OBJS = main.o

PSPSDK = $(shell psp-config --pspsdk-path)
PSPBIN = $(shell psp-config --psp-prefix)/bin
SDL_CONFIG = $(PSPBIN)/sdl-config

CFLAGS = -Wall -Wextra $(shell $(SDL_CONFIG) --cflags)
CXXFLAGS = $(CFLAGS)

LIBS = $(shell $(SDL_CONFIG) --libs)

EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = Main

include $(PSPSDK)/lib/build.mak
